#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <canutils_icons.h>

int32_t canutils_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm canutils!");

    return 0;
}
